language: python
python:
  - "3.6"

before_install:
    - sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -U pytest
        
script:
  - python pyslide/hello.py
