version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.1

        working_directory: ~/repo

        steps:
            - checkout
            - run:
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install scipy
                    pip install matplotlib
                    pip install -U pytest
            - run:
                name: run tests
                command: |
                    . venv/bin/activate
                    cd test
                    pytest .

            - store_artifacts:
                path: test-reports
                destination: test-reports
